### ISSUE TITLE
`open` doesn't work on some user machines, why not use `electron.shell.openPath`?

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/auth-clients#108]
Can we switch from using [`open`](https://www.npmjs.com/package/open#openapps) [here](https://github.com/iTwin/auth-clients/blob/787f2bd24bf96f83f3246729a5ddab4696486752/packages/electron/src/main/ElectronMainAuthorizationRequestHandler.ts#L64)
to `electron.shell.openPath`, as recommended in the README of `open` itself?

I have found users where `open` doesn't work to open the browser (as it's used here anyway), where as electron's `shell.openPath` works fine.

**Comment by ben-polinsky** [comment]
Reopening as `openPath` is incorrect - that is for paths not urls. `openExternal` is the way to go.

**Comment by MichaelBelousov** [comment]
Is there a timeline for a fix for this The current latest version of the desktop auth client doesn't work on linux and mac. Can reproduce on a desktop application I'm working on which is using the latest (@itwin/electron-authorization@0.13.0)

**Comment by MichaelBelousov** [comment]
I wouldn't describe it as urgent on my end @ben-polinsky, just been a bit and wanted to make sure it's still being worked on. Can wait for the larger PR too.

**Comment by ben-polinsky** [comment]
Definitely a priority.

**Comment by MichaelBelousov** [comment]
A colleague confirmed using `openExternal` works on windows.

**Comment by ben-polinsky** [comment]
merged.. waiting for release

**Comment by ben-polinsky** [comment]
This is released in @itwin/electron-authorization@0.14.0
