### ISSUE TITLE
[electron client] Breaking changes before stable release

### ISSUE THREAD

**Issue by karolis-zukauskas** [iTwin/auth-clients#113]
I would like to introduce some breaking changes before we release a stable version (1.0.0) of `@itwin/electron-authorization`.

- Use dynamic channel names when setting up IPC (e.g. based on clientId).
  - Currently constructing a second instance of `ElectronMainAuthorization` will cause an error due to duplicate handlers (`ipcMain.handle(...)`).
- Make `ElectronMainAuthorization` dependency on `ipcMain` optional (e.g. accept an optional `IpcSocket` implementation to use for the IPC calls)
  - In iTwin Studio we found that hosting backend-core in Electron "main" process causes UI issues, instead we are hosting it in Electron "utility" process (which doesn't have access to `ipcMain`).
- Remove unconditional inclusion of `offline_access` scope
  - General change - I don't think this package should make assumptions about client scope needs.
- By default use `prompt=login` instead of `prompt=consent` extra URL parameter.
  - `prompt=consent` parameter causes the consent page to be always shown, even if the OIDC Client has it disabled. In most cases, consent page for Bentley applications (i.e. 1st party applications) doesn't make sense. `prompt=login` will only show a login page (enter credentials) and skip the consent page (if Client has it setup).
- Remove `access_type=offline` extra URL parameter
  - This doesn't seem to be part of OIDC protocol (perhaps IMS specific?) and doesn't seem to have an effect on authorization (at least I didn't notice that). Laurynas R. suggested that this is most likely a copy paste from some other implementation and should not belong in our code.
- Use `string[]` instead of `string` for `redirectUri` in `ElectronMainAuthorizationConfiguration`
  - This is based on recent discussion on redirect URI guidelines with AppSec team. Official guidelines are coming soon, but in short desktop/native apps should stick to using http loopback and should have multiple redirect URIs to avoid port collisions. I would like to explicitly break the API here so that consumers (hopefully) update their OIDC configurations to include multiple redirect URIs based on upcoming guidelines.
  
@aruniverse, @calebmshafer, @kckst8, @ben-polinsky , @GytisCepk  - Let me know what you think about proposed changes.

**Comment by ben-polinsky** [comment]
On initial look, these changes make sense to me.  Definitely interested in the upcoming guidance :)
