### ISSUE TITLE
Replace Keytar (Electron)

### ISSUE THREAD

**Issue by ben-polinsky** [iTwin/auth-clients#161]
[Keytar](https://github.com/atom/node-keytar) has been deprecated to the dismay of everyone in the universe. We need to identify a replacement or fork.

**Comment by ben-polinsky** [comment]
https://www.electronjs.org/docs/latest/api/safe-storage

**Comment by aruniverse** [comment]
> [electronjs.org/docs/latest/api/safe-storage](https://www.electronjs.org/docs/latest/api/safe-storage)

looks like thats what vscode is switching too as well, https://code.visualstudio.com/updates/v1_80#_secretstorage-api-now-uses-electron-api-over-keytar
