### ISSUE TITLE
Unable to import ElectronRendererAuthorization after recent subpaths change

### ISSUE THREAD

**Issue by GintV** [iTwin/auth-clients#205]
I am unable to import ElectronRendererAuthorization on @itwin/electron-authorization v0.16.0 . I think it is related with #195 . I tried importing it in all sorts of ways and paths, but webpack fails to find it. Trying to import it using the @itwin/electron-authorization/Renderer path, I am getting this message from webpack

![image](https://github.com/iTwin/auth-clients/assets/17436829/b5351f84-05ae-4d5b-a40c-92da43f17b37)

It is funny that it mentions exports field since I am importing based on that export field. I am using Bentley fork of react-scripts to build frontend.

**Comment by aruniverse** [comment]
> I tried importing it in all sorts of ways and paths

can you please share what you tried?

**Comment by GintV** [comment]
I tried 

```
... from "@itwin/electron-authorization/Renderer";
... from "@itwin/electron-authorization/lib/esm/renderer/Client";
... from "@itwin/electron-authorization";
```

This is our tsconfig.json used for Bentley fork of react-scritps

```
{
  "extends": "./node_modules/@itwin/build-tools/tsconfig-base.json",
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "declarationMap": false,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "module": "esnext",
    "noEmit": true,
    "outDir": "./lib",
    "plugins": [
      {
        "name": "typescript-plugin-css-modules"
      }
    ],
    "types": [
      "@bentley/react-scripts",
    ],
  },
  "include": [
    "./src/common/**/*.ts",
    "./src/frontend/**/*.ts",
    "./src/frontend/**/*.tsx"
  ],
  "exclude": [
    "./src/backend/**/*.ts"
  ]
}

```

**Comment by aruniverse** [comment]
Use the following recommended tsconfigs:

Frontend: 

``` 
    "module": "ESNext",
    "moduleResolution": "Bundler",
```

[ESNext](https://www.typescriptlang.org/tsconfig#esnext)
[Bundler](https://www.typescriptlang.org/tsconfig#moduleResolution)

Backend:

``` 
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
```

[NodeNext](https://www.typescriptlang.org/tsconfig#node16nodenext-nightly-builds)
[NodeNext](https://www.typescriptlang.org/tsconfig#moduleResolution)

**Comment by aruniverse** [comment]
take a look at the example: https://github.com/iTwin/itwinjs-core/pull/6058

**Comment by GintV** [comment]
We recently made the tsconfig updates and I thought that it might allow us to use latest electron-auth package version. I just tested and everything works now. I am closing this issue.
