### ISSUE TITLE
`@itwin/oidc-signin-tool` password is not always filled in

### ISSUE THREAD

**Issue by johnnyd710** [iTwin/auth-clients#224]
Sometimes (not all the time) in our MacOS Github Action, the password is not filled out in the sign-in form using `@itwin/oidc-signin-tool` with our Electron application. I was able to catch a video of it after a few attempts. In the third second of the video you will see "Please fill out this field." and the password is not filled in, I attached a screenshot of the moment.

![image](https://github.com/iTwin/auth-clients/assets/19596966/10ce904c-1250-414c-bd7f-cf7a7e0fc068)

https://github.com/iTwin/auth-clients/assets/19596966/a9dbd2c2-bbd0-44a4-853a-f349541cf578

Reach out to me if you have any questions.

**Comment by johnnyd710** [comment]
I patched the `oidc-signin-tools` package to take a screenshot and dump the html to a file right before we enter the password. Problem is, I can't reproduce anymore after 4 attempts.

Its possible there is a race condition, and the time it takes to take the screenshot and dump the html to a file fixes the problem.

**Comment by MichaelBelousov** [comment]
4 attempts doesn't seem like enough based on what I know about our CI...
but yes the HTML probably hurts the odds, perhaps significantly... can you make the CI try it on loop more times?

**Comment by johnnyd710** [comment]
I *think* replacing the `.type` calls with `.fill` helped, my CI keeps failing for other reasons so its hard to be sure, but I haven't seen the error in a few runs with repeatEach set to 5
