### ISSUE TITLE
`process` is not available in the browser

### ISSUE THREAD

**Issue by veekeys** [iTwin/auth-clients#241]
<img width="564" alt="image" src="https://github.com/iTwin/auth-clients/assets/81580355/6154e85b-a566-46fa-a526-bd72e3493ddb">

Getting this with the newest `@itwin/browser-authorization` version. Probably, should not rely on environment variables for the resolution of authority...

**Comment by ben-polinsky** [comment]
Thanks. 

This is due to our earlier reliance on webpack/cra magic and has not been caught as the `getImsAuthority` method is only called as a fallback.

**Comment by ben-polinsky** [comment]
@veekeys Could you test out the fix in `v1.1.1`?

**Comment by ben-polinsky** [comment]
Closing, please let us know if the issue is not resolved.

**Comment by veekeys** [comment]
@ben-polinsky Sorry, checked now, seems that error is gone.
Thanks!

**Comment by ben-polinsky** [comment]
np! Thanks for testing.
