### ISSUE TITLE
bug: electron app e2e test hangs while using `oidc-signin-tool`

### ISSUE THREAD

**Issue by johnnyd710** [iTwin/auth-clients#262]
The test hangs at this line: https://github.com/iTwin/auth-clients/blob/main/packages/oidc-signin-tool/src/SignInAutomation.ts#L169. Commenting out *all* 'networkidle' lines in a patch fix solves the issue. 

Playwright's [waitForLoadState('networkidle') is discouraged](https://playwright.dev/docs/api/class-page#page-wait-for-load-state). I think the package should be refactored to avoid using it.

**Comment by johnnyd710** [comment]
@MichaelSwigerAtBentley can we close this now? seems to be working.

**Comment by MichaelSwigerAtBentley** [comment]
Yes. There are still some 'networkidle' calls in the integration tests that I would like to remove, but I will create a new issue to track that.
