### ISSUE TITLE
Add ability for oidc-signin-tool's certa backend to retrieve an accessToken through service clients

### ISSUE THREAD

**Issue by hl662** [iTwin/auth-clients#271]
Feature request stemming from https://github.com/iTwin/itwinjs-core/issues/7300

We tried switching over to using 'service-authorization' in the our full stack tests, and building the tests fail - I'm fairly certain it's because the full stack tests are using playwright's chromium instance to run the tests, and those don't have node APIs available, which service-authorization uses. This would explain why we haven't used service auth in our full stack tests in the past, instead using TestFrontendAuthorizationClient, with an accessToken provided through [getAccessTokenFromBackend()](https://github.com/iTwin/itwinjs-core/blob/c638ded39bdce3c46c2c149e3bcce91420db3811/full-stack-tests/rpc-interface/src/frontend/setup/TestContext.ts#L64). That method is implemented in `oidc-signin-tool` [certaCommon](https://github.com/iTwin/auth-clients/blob/88e2185c6df25034738d2791af8b4dccd093eb4c/packages/oidc-signin-tool/src/certa/certaCommon.ts#L15), which executes a backend callback to certa's backend. The backend then [uses](https://github.com/iTwin/auth-clients/blob/88e2185c6df25034738d2791af8b4dccd093eb4c/packages/oidc-signin-tool/src/certa/certaBackend.ts#L47-L48) playwright and a `TestBrowserAuthorizationClient` to sign in and retrieve an access token. We should expose an additional way in oidc-signin-tool's certaBackend.ts, that instead uses a ServiceAuthorizationClient to retrieve an accessToken. 

This use case is closely tied for use in our tests that run through certa.

**Comment by ben-polinsky** [comment]
I suppose we're not killing certa off anytime soon?

**Comment by hl662** [comment]
not until we figure out a good way to handle full stack tests without it...
