### ISSUE TITLE
Improve or allow customization of the Electron LoopbackWebServer response pages

### ISSUE THREAD

**Issue by RaphaelMelancon** [iTwin/auth-clients#80]
The pages presented to the user for successful sign-in and error authentication error are plain white pages that contrast with the iTwin UI standards and/or authenticating application.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/98826280/177570405-52164968-e196-4943-9e8b-432ed90bdb33.png)

Please allow for a way to customize the look of this page or make it adhere to [iTwin UI](https://ux.bentley.com/itwin/about.html) standards.

**Comment by calebmshafer** [comment]
@RaphaelMelancon I definitely agree with the need to change this log-out page as it doesn't look great. However, it is driven by IMS (Bentley's IdP) so this won't be a simple change within the library. We will need to raise this internally.

**Comment by ben-polinsky** [comment]
> @RaphaelMelancon I definitely agree with the need to change this log-out page as it doesn't look great. However, it is driven by IMS (Bentley's IdP) so this won't be a simple change within the library. We will need to raise this internally.

We actually control the "signed in, now return to your app" page in both node and electron packages. Look at the snazzy page fly.io presents - something like this would be awesome:

![image](https://github.com/iTwin/auth-clients/assets/78756012/c05f315e-000e-47fd-9a47-8e5a071838b5)
